# Generated by Django 5.2.10 on 2026-01-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_index', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(db_index=True, default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='wall.wallprofile')),
            ],
            options={
                'ordering': ['profile', 'section_index'],
                'unique_together': {('profile', 'section_index')},
            },
        ),
    ]
