# Generated by Django 5.2.10 on 2026-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_wallsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='day_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='wallprofile',
            name='profile_number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
